# Generated by Django 4.1 on 2022-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=19)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
