# Generated by Django 4.1 on 2022-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
