# Generated by Django 4.1 on 2022-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_curr_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=19), max_digits=19),
        ),
    ]
