# Generated by Django 4.1 on 2022-09-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_curr_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.listing'),
        ),
    ]
