# Generated by Django 4.1 on 2022-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bought',
        ),
        migrations.AddField(
            model_name='user',
            name='bought',
            field=models.ManyToManyField(blank=True, related_name='owner', to='auctions.listing'),
        ),
    ]
